version: "3.8"

services:

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 20

  datadog:
    image: datadog/agent:latest
    environment:
      DD_API_KEY: "4e040f2fee6f2337ce4a56646eccb1fc"
      DD_SITE: "us5.datadoghq.com"
      DD_LOGS_ENABLED: "true"
      DD_APM_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_BIND_HOST: "0.0.0.0"
    ports:
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - kafka
      - datadog
  ml-api:
    build:
      context: .
      dockerfile: ml-api/Dockerfile

    ports:
      - "8000:8000"

  silver:
  build:
    context: .
    dockerfile: lake/plata/Dockerfile

  depends_on:
    - minio

  gold:
    build:
      context: .
      dockerfile: lake/oro/Dockerfile

    depends_on:
      - minio
      - ml-api